/* Built-in exercise library — browse and add to "My exercises" with one tap.
   You can attach your own photos/videos to any of these after adding. */
window.EXERCISE_LIBRARY = [
  // ---- Chest ----
  { name: 'Bench Press', group: 'Chest', notes: 'Barbell to mid-chest, elbows ~45°, feet planted, press up and slightly back.' },
  { name: 'Incline Dumbbell Press', group: 'Chest', notes: 'Bench at 30–45°. Press dumbbells up and together, control the descent.' },
  { name: 'Dumbbell Fly', group: 'Chest', notes: 'Slight elbow bend, open arms wide until chest stretch, squeeze back up.' },
  { name: 'Push-Up', group: 'Chest', notes: 'Body in one line, hands under shoulders, chest to floor, full lockout.' },
  { name: 'Cable Crossover', group: 'Chest', notes: 'Step forward, slight lean, bring handles together in an arc, squeeze chest.' },
  { name: 'Chest Dip', group: 'Chest', notes: 'Lean torso forward, elbows out slightly, lower until shoulder stretch.' },
  { name: 'Machine Chest Press', group: 'Chest', notes: 'Seat so handles are at mid-chest. Press smoothly, don’t lock elbows hard.' },

  // ---- Back ----
  { name: 'Pull-Up', group: 'Back', notes: 'Full hang to chin over bar, chest up, pull elbows to ribs.' },
  { name: 'Lat Pulldown', group: 'Back', notes: 'Grip wider than shoulders, pull bar to upper chest, no swinging.' },
  { name: 'Barbell Row', group: 'Back', notes: 'Hinge ~45°, flat back, pull bar to lower ribs, squeeze shoulder blades.' },
  { name: 'Dumbbell Row', group: 'Back', notes: 'One knee and hand on bench, flat back, row to hip, slow negative.' },
  { name: 'Seated Cable Row', group: 'Back', notes: 'Chest tall, pull handle to stomach, shoulders back and down.' },
  { name: 'T-Bar Row', group: 'Back', notes: 'Chest on pad or hinged stance, drive elbows back, squeeze mid-back.' },
  { name: 'Face Pull', group: 'Back', notes: 'Rope at face height, pull towards eyes, elbows high, external rotate.' },
  { name: 'Deadlift', group: 'Back', notes: 'Bar over mid-foot, flat back, push floor away, finish tall with hips.' },
  { name: 'Back Extension', group: 'Back', notes: 'Hinge at hips on the pad, raise torso to straight line, don’t hyperextend.' },

  // ---- Shoulders ----
  { name: 'Overhead Press', group: 'Shoulders', notes: 'Barbell at collarbone, brace core, press overhead to lockout.' },
  { name: 'Dumbbell Shoulder Press', group: 'Shoulders', notes: 'Seated or standing, press dumbbells up without flaring ribs.' },
  { name: 'Lateral Raise', group: 'Shoulders', notes: 'Slight elbow bend, raise to shoulder height, lead with elbows, light weight.' },
  { name: 'Front Raise', group: 'Shoulders', notes: 'Raise dumbbell/plate to eye level with straight arms, no swinging.' },
  { name: 'Rear Delt Fly', group: 'Shoulders', notes: 'Hinge forward, open arms wide, squeeze rear shoulders, light weight.' },
  { name: 'Arnold Press', group: 'Shoulders', notes: 'Start palms facing you, rotate out while pressing overhead.' },
  { name: 'Upright Row', group: 'Shoulders', notes: 'Pull bar/dumbbells to chest height, elbows lead, grip shoulder-width.' },
  { name: 'Shrug', group: 'Shoulders', notes: 'Heavy dumbbells/bar, shoulders straight up to ears, pause, lower slow.' },

  // ---- Arms ----
  { name: 'Barbell Curl', group: 'Arms', notes: 'Elbows pinned at sides, curl up without swinging, full stretch at bottom.' },
  { name: 'Dumbbell Curl', group: 'Arms', notes: 'Alternate or together, supinate wrist on the way up, control down.' },
  { name: 'Hammer Curl', group: 'Arms', notes: 'Neutral grip (palms facing in), curl to shoulder, hits forearm too.' },
  { name: 'Preacher Curl', group: 'Arms', notes: 'Arms on pad, curl with strict form, stretch fully at the bottom.' },
  { name: 'Triceps Pushdown', group: 'Arms', notes: 'Cable rope/bar, elbows pinned, extend fully and squeeze, control up.' },
  { name: 'Skull Crusher', group: 'Arms', notes: 'Lying, lower bar to forehead with still upper arms, extend back up.' },
  { name: 'Overhead Triceps Extension', group: 'Arms', notes: 'Dumbbell overhead with both hands, lower behind head, extend up.' },
  { name: 'Close-Grip Bench Press', group: 'Arms', notes: 'Hands shoulder-width, elbows tucked, press focusing on triceps.' },
  { name: 'Concentration Curl', group: 'Arms', notes: 'Seated, elbow braced on inner thigh, strict slow curls.' },

  // ---- Legs ----
  { name: 'Squat', group: 'Legs', notes: 'Bar on upper back, feet shoulder-width, sit down between hips, drive up.' },
  { name: 'Front Squat', group: 'Legs', notes: 'Bar on front delts, elbows high, torso upright, squat deep.' },
  { name: 'Goblet Squat', group: 'Legs', notes: 'Hold dumbbell at chest, squat deep between knees, chest tall.' },
  { name: 'Leg Press', group: 'Legs', notes: 'Feet shoulder-width on platform, lower to 90°+, don’t lock knees hard.' },
  { name: 'Lunge', group: 'Legs', notes: 'Big step forward, back knee toward floor, push through front heel.' },
  { name: 'Bulgarian Split Squat', group: 'Legs', notes: 'Rear foot on bench, drop straight down, front shin vertical.' },
  { name: 'Romanian Deadlift', group: 'Legs', notes: 'Soft knees, push hips back, bar close to legs, feel hamstring stretch.' },
  { name: 'Leg Extension', group: 'Legs', notes: 'Extend to full lockout, squeeze quads, lower slowly.' },
  { name: 'Leg Curl', group: 'Legs', notes: 'Curl heels to glutes, pause, resist on the way back.' },
  { name: 'Hip Thrust', group: 'Legs', notes: 'Upper back on bench, bar on hips, drive hips to full lockout, squeeze glutes.' },
  { name: 'Calf Raise', group: 'Legs', notes: 'Full stretch at bottom, pause at top, slow reps beat bouncing.' },
  { name: 'Step-Up', group: 'Legs', notes: 'Knee-height box, drive through the top leg, control the way down.' },
  { name: 'Sumo Deadlift', group: 'Legs', notes: 'Wide stance, toes out, grip inside knees, chest up, push floor apart.' },

  // ---- Core ----
  { name: 'Plank', group: 'Core', notes: 'Elbows under shoulders, body in one line, squeeze glutes, breathe. Log seconds as reps.' },
  { name: 'Side Plank', group: 'Core', notes: 'Stacked feet, hips high, hold. Log seconds as reps, both sides.' },
  { name: 'Crunch', group: 'Core', notes: 'Curl shoulder blades off floor, exhale up, don’t pull the neck.' },
  { name: 'Bicycle Crunch', group: 'Core', notes: 'Opposite elbow to knee, slow and controlled, full extension of the free leg.' },
  { name: 'Hanging Leg Raise', group: 'Core', notes: 'Dead hang, raise legs to 90°+ without swinging, lower slow.' },
  { name: 'Russian Twist', group: 'Core', notes: 'Seated lean-back, rotate side to side, add weight to progress.' },
  { name: 'Cable Crunch', group: 'Core', notes: 'Kneel, rope behind head, crunch ribs to hips, hips stay still.' },
  { name: 'Ab Wheel Rollout', group: 'Core', notes: 'From knees, roll out as far as control allows, no sagging hips.' },
  { name: 'Mountain Climbers', group: 'Core', notes: 'Plank position, drive knees to chest fast, hips low.' },
  { name: 'Dead Bug', group: 'Core', notes: 'On back, lower opposite arm and leg, lower back stays flat on floor.' },

  // ---- Cardio ----
  { name: 'Treadmill Run', group: 'Cardio', notes: 'Log minutes as reps. Easy pace = conversation possible; intervals = hard/easy.' },
  { name: 'Cycling', group: 'Cardio', notes: 'Log minutes as reps. Keep cadence ~80–100 rpm.' },
  { name: 'Rowing Machine', group: 'Cardio', notes: 'Legs → back → arms, then reverse. Log minutes or meters as reps.' },
  { name: 'Jump Rope', group: 'Cardio', notes: 'Small hops, wrists do the work. Log seconds or jumps as reps.' },
  { name: 'Stair Climber', group: 'Cardio', notes: 'Log minutes as reps. Stand tall, light grip on rails.' },
  { name: 'Elliptical', group: 'Cardio', notes: 'Log minutes as reps. Push and pull the handles for full body.' },
  { name: 'Swimming', group: 'Cardio', notes: 'Log minutes or laps as reps.' },
  { name: 'HIIT Sprints', group: 'Cardio', notes: 'e.g. 30s all-out / 90s easy. Log rounds as sets, seconds as reps.' },

  // ---- Full body ----
  { name: 'Burpee', group: 'Full body', notes: 'Squat, kick back to plank, push-up, jump up. Steady rhythm.' },
  { name: 'Kettlebell Swing', group: 'Full body', notes: 'Hip hinge, snap hips forward, bell floats to chest height, arms relaxed.' },
  { name: 'Clean and Press', group: 'Full body', notes: 'Explosive pull to shoulders, then press overhead, reset each rep.' },
  { name: 'Thruster', group: 'Full body', notes: 'Front squat straight into overhead press, one fluid motion.' },
  { name: 'Farmer’s Carry', group: 'Full body', notes: 'Heavy dumbbells at sides, walk tall. Log meters or seconds as reps.' },
  { name: 'Wall Ball', group: 'Full body', notes: 'Squat then throw ball to target, catch and repeat in rhythm.' },
  { name: 'Battle Ropes', group: 'Full body', notes: 'Alternating or double waves, athletic stance. Log seconds as reps.' }
];

/* Demo animation slugs (2-frame photos in demos/<slug>/0.jpg + 1.jpg,
   from the public-domain free-exercise-db dataset). */
window.EXERCISE_DEMOS = {
  "Ab Wheel Rollout": "ab-wheel-rollout",
  "Arnold Press": "arnold-press",
  "Back Extension": "back-extension",
  "Barbell Curl": "barbell-curl",
  "Barbell Row": "barbell-row",
  "Battle Ropes": "battle-ropes",
  "Bench Press": "bench-press",
  "Bicycle Crunch": "bicycle-crunch",
  "Bulgarian Split Squat": "bulgarian-split-squat",
  "Cable Crossover": "cable-crossover",
  "Cable Crunch": "cable-crunch",
  "Calf Raise": "calf-raise",
  "Chest Dip": "chest-dip",
  "Clean and Press": "clean-and-press",
  "Close-Grip Bench Press": "close-grip-bench-press",
  "Concentration Curl": "concentration-curl",
  "Crunch": "crunch",
  "Cycling": "cycling",
  "Dead Bug": "dead-bug",
  "Deadlift": "deadlift",
  "Dumbbell Curl": "dumbbell-curl",
  "Dumbbell Fly": "dumbbell-fly",
  "Dumbbell Row": "dumbbell-row",
  "Dumbbell Shoulder Press": "dumbbell-shoulder-press",
  "Elliptical": "elliptical",
  "Face Pull": "face-pull",
  "Farmer's Carry": "farmer-s-carry",
  "Front Raise": "front-raise",
  "Front Squat": "front-squat",
  "Goblet Squat": "goblet-squat",
  "HIIT Sprints": "hiit-sprints",
  "Hammer Curl": "hammer-curl",
  "Hanging Leg Raise": "hanging-leg-raise",
  "Hip Thrust": "hip-thrust",
  "Incline Dumbbell Press": "incline-dumbbell-press",
  "Jump Rope": "jump-rope",
  "Kettlebell Swing": "kettlebell-swing",
  "Lat Pulldown": "lat-pulldown",
  "Lateral Raise": "lateral-raise",
  "Leg Curl": "leg-curl",
  "Leg Extension": "leg-extension",
  "Leg Press": "leg-press",
  "Lunge": "lunge",
  "Machine Chest Press": "machine-chest-press",
  "Mountain Climbers": "mountain-climbers",
  "Overhead Press": "overhead-press",
  "Overhead Triceps Extension": "overhead-triceps-extension",
  "Plank": "plank",
  "Preacher Curl": "preacher-curl",
  "Pull-Up": "pull-up",
  "Push-Up": "push-up",
  "Rear Delt Fly": "rear-delt-fly",
  "Romanian Deadlift": "romanian-deadlift",
  "Rowing Machine": "rowing-machine",
  "Russian Twist": "russian-twist",
  "Seated Cable Row": "seated-cable-row",
  "Shrug": "shrug",
  "Side Plank": "side-plank",
  "Skull Crusher": "skull-crusher",
  "Squat": "squat",
  "Stair Climber": "stair-climber",
  "Step-Up": "step-up",
  "Sumo Deadlift": "sumo-deadlift",
  "T-Bar Row": "t-bar-row",
  "Thruster": "thruster",
  "Treadmill Run": "treadmill-run",
  "Triceps Pushdown": "triceps-pushdown",
  "Upright Row": "upright-row",
  "Wall Ball": "wall-ball"
};
window.EXERCISE_LIBRARY.forEach(item => {
  const d = window.EXERCISE_DEMOS[item.name];
  if (d) item.demo = d;
});

/* Additional exercises used by the starter block */
[
  { name: 'Chest-Supported Row', group: 'Back', notes: 'Chest stays on the pad the whole set — zero spinal load. Drive elbows back, squeeze mid-back.', demo: 'chest-supported-row' },
  { name: 'Machine Shoulder Press', group: 'Shoulders', notes: 'Back flat on the pad, press smoothly overhead, don’t lock out hard.', demo: 'machine-shoulder-press' },
  { name: 'Assisted Pull-Up', group: 'Back', notes: 'Use the assist machine or a band. Full hang to chin over bar, chest up. Or do a lat pulldown.', demo: 'assisted-pull-up' },
  { name: 'Glute Bridge', group: 'Legs', notes: 'On the floor, bodyweight. Drive hips up, squeeze glutes at the top, lower slow. Back stays neutral.', demo: 'glute-bridge' },
  { name: 'Pallof Press', group: 'Core', notes: 'Cable at chest height, press arms straight out and resist the twist. Log reps per side.', demo: 'pallof-press' }
].forEach(item => window.EXERCISE_LIBRARY.push(item));

/* Everything else that has written content in data/exercise-content.json.
   Generated from data/exercise-library.json — the entries above are older and
   hand-written, so they are left exactly as they were. Items without a clip in
   demos/ fall back to the placeholder thumbnail. */
[
  { name: "Low Bar Back Squat", group: "Legs", notes: "Back squat with the bar carried lower on the shoulders, shifting work toward the hips and allowing heavier loads." },
  { name: "Box Squat", group: "Legs", notes: "Squat to a set box height, teaching consistent depth and heavy hip loading with a pause at the bottom." },
  { name: "Safety Squat Bar Squat", group: "Legs", notes: "Squat with a cambered, padded bar that sits on the shoulders with handles in front — no shoulder mobility needed." },
  { name: "Dumbbell Squat", group: "Legs", notes: "Squat holding a dumbbell in each hand at the sides, limited by grip rather than leg strength." },
  { name: "Smith Machine Squat", group: "Legs", notes: "Squat on a fixed bar path, which removes the balance demand and lets you place the feet forward." },
  { name: "Hack Squat Machine", group: "Legs", notes: "Plate-loaded sled squat with the back supported on a pad, loading the quads through a deep knee bend." },
  { name: "Pendulum Squat", group: "Legs", notes: "Machine squat on an arcing path that keeps resistance high through the bottom of the range." },
  { name: "Belt Squat", group: "Legs", notes: "Squat with the load hung from a hip belt, so the legs work hard with nothing carried on the spine." },
  { name: "Single-Leg Press", group: "Legs", notes: "Leg press performed one leg at a time, exposing and correcting side-to-side differences with the back supported." },
  { name: "Bodyweight Squat", group: "Legs", notes: "Unloaded squat used to learn the pattern, warm up, or train legs with no equipment at all." },
  { name: "Wall Sit", group: "Legs", notes: "Isometric hold at squat depth with the back against a wall, training the quads under time rather than reps." },
  { name: "Pistol Squat", group: "Legs", notes: "Full-depth single-leg squat with the other leg held out in front, demanding strength, balance and ankle mobility together." },
  { name: "Trap Bar Deadlift", group: "Legs", notes: "Deadlift from inside a hexagonal bar with neutral handles, easier to learn and kinder to the lower back." },
  { name: "Dumbbell Romanian Deadlift", group: "Legs", notes: "Romanian deadlift with dumbbells, easier to keep close to the body and simpler to learn than the barbell version." },
  { name: "Single-Leg Romanian Deadlift", group: "Legs", notes: "Hip hinge balanced on one leg, training the hamstrings and glutes while exposing side-to-side differences." },
  { name: "Stiff-Leg Deadlift", group: "Legs", notes: "Deadlift from the floor with near-straight legs, loading the hamstrings through the longest range of any hinge." },
  { name: "Deficit Deadlift", group: "Legs", notes: "Deadlift performed standing on a raised platform, adding range at the bottom to attack the first inch off the floor." },
  { name: "Rack Pull", group: "Legs", notes: "Partial deadlift starting with the bar raised on pins or blocks, overloading the top half of the pull." },
  { name: "Good Morning", group: "Legs", notes: "Hip hinge with the bar on the back, loading the hamstrings and spinal erectors through a long lever." },
  { name: "Hip Thrust Machine", group: "Legs", notes: "Hip thrust on a dedicated machine, with the setup handled for you and the load easy to change." },
  { name: "Glute-Ham Raise", group: "Legs", notes: "Bodyweight hamstring curl performed on a glute-ham developer, combining knee flexion with hip extension." },
  { name: "Nordic Hamstring Curl", group: "Legs", notes: "Kneeling eccentric hamstring curl with the ankles held, one of the strongest protective exercises for the hamstrings." },
  { name: "Reverse Hyperextension", group: "Legs", notes: "Machine hip extension performed lying face down, loading the glutes and lower back with traction rather than compression." },
  { name: "Cable Pull-Through", group: "Legs", notes: "Cable hinge that teaches the hip pattern with the resistance pulling backwards instead of down." },
  { name: "Walking Lunge", group: "Legs", notes: "Lunging forward step after step, alternating legs while carrying the load and moving continuously." },
  { name: "Reverse Lunge", group: "Legs", notes: "Lunge stepping backwards instead of forwards, which is far kinder on the knees than the forward version." },
  { name: "Split Squat", group: "Legs", notes: "Stationary lunge with both feet planted, the simplest way to load one leg at a time." },
  { name: "Lateral Lunge", group: "Legs", notes: "Stepping sideways into a single-leg squat, one of the few exercises that loads the adductors through range." },
  { name: "Curtsy Lunge", group: "Legs", notes: "Lunge stepping diagonally behind the standing leg, biasing the glute medius and outer hip." },
  { name: "Smith Machine Split Squat", group: "Legs", notes: "Split squat on a fixed bar path, removing the balance demand so the working leg can be loaded properly." },
  { name: "Incline Barbell Bench Press", group: "Chest", notes: "Barbell press on an inclined bench, shifting emphasis toward the upper chest and front delts." },
  { name: "Decline Barbell Bench Press", group: "Chest", notes: "Barbell press on a declined bench, emphasising the lower chest through a shorter range." },
  { name: "Floor Press", group: "Chest", notes: "A bench press from the floor that stops the range at the triceps lockout portion." },
  { name: "Dumbbell Bench Press", group: "Chest", notes: "A flat press with two independent dumbbells, allowing a deeper and more natural path." },
  { name: "Smith Machine Bench Press", group: "Chest", notes: "A bench press on a fixed vertical bar path, with catch hooks at every height." },
  { name: "Incline Push-Up", group: "Chest", notes: "A push-up with the hands raised, reducing the load so the line can be held." },
  { name: "Deficit Push-Up", group: "Chest", notes: "A push-up from raised hands, letting the chest travel below the hands." },
  { name: "Assisted Dip Machine", group: "Chest", notes: "A dip machine that carries part of your bodyweight so the reps can be built up." },
  { name: "Pec Deck / Machine Fly", group: "Chest", notes: "A machine chest fly with a fixed arc and a back pad." },
  { name: "Push Press", group: "Shoulders", notes: "An overhead press driven off a short leg dip, moving far more weight than a strict press." },
  { name: "Seated Dumbbell Press", group: "Shoulders", notes: "A dumbbell overhead press from a supported seat, removing the trunk from the equation." },
  { name: "Landmine Press", group: "Shoulders", notes: "A single-arm press on an angled bar, halfway between overhead and horizontal." },
  { name: "Seated Z-Press", group: "Shoulders", notes: "An overhead press seated on the floor with the legs straight out in front." },
  { name: "Pike Push-Up", group: "Shoulders", notes: "A push-up with the hips piked high, turning it into a bodyweight overhead press." },
  { name: "Handstand Push-Up", group: "Shoulders", notes: "An overhead press performed upside down, pressing your full bodyweight." },
  { name: "Chin-Up", group: "Back", notes: "A pull-up with the palms facing you, sharing the work between lats and biceps." },
  { name: "Neutral-Grip Pull-Up", group: "Back", notes: "A pull-up on parallel handles with the palms facing each other." },
  { name: "Close-Grip Lat Pulldown", group: "Back", notes: "A pulldown on a narrow neutral or underhand grip, biased to the lower lat." },
  { name: "Single-Arm Lat Pulldown", group: "Back", notes: "A one-arm cable pulldown, with a longer range and no stronger side to hide behind." },
  { name: "Straight-Arm Pulldown", group: "Back", notes: "A cable pulldown with locked elbows, isolating the lats without the biceps." },
  { name: "Seated Row Machine", group: "Back", notes: "A guided seated row with a chest pad and a fixed path." },
  { name: "Inverted Row", group: "Back", notes: "A bodyweight row under a fixed bar, the horizontal counterpart to a pull-up." },
  { name: "Suspension Trainer Row", group: "Back", notes: "A bodyweight row on suspension straps, adjustable by simply walking the feet." },
  { name: "Meadows Row", group: "Back", notes: "A single-arm row on the end of a landmine bar, taken from a staggered stance." },
  { name: "Seal Row", group: "Back", notes: "A barbell row lying face down on a raised bench, with the torso completely fixed." },
  { name: "Cable Lateral Raise", group: "Shoulders", notes: "A one-arm lateral raise on a low cable, with tension held at the bottom." },
  { name: "Lateral Raise Machine", group: "Shoulders", notes: "A guided lateral raise with pads on the upper arms and a fixed arc." },
  { name: "Rear Delt Fly Machine", group: "Shoulders", notes: "A reverse pec deck, isolating the rear delts with the chest supported." },
  { name: "Dumbbell Shrug", group: "Shoulders", notes: "A shrug with a dumbbell in each hand, the load hanging beside the body." },
  { name: "Cable External Rotation", group: "Shoulders", notes: "A light cable rotation outward, training the rotator cuff directly." },
  { name: "Band Pull-Apart", group: "Back", notes: "A band stretched apart at chest height, training the rear delts and mid-back." },
  { name: "EZ-Bar Curl", group: "Arms", notes: "A barbell curl on a cambered bar, easier on the wrists and elbows." },
  { name: "Incline Dumbbell Curl", group: "Arms", notes: "A curl lying back on an incline bench, with the arms hanging behind the body." },
  { name: "Cable Biceps Curl", group: "Arms", notes: "A biceps curl against a low cable, with tension held through the whole range." },
  { name: "Biceps Curl Machine", group: "Arms", notes: "A guided biceps curl with the arms on a pad and a fixed arc." },
  { name: "Reverse Curl", group: "Arms", notes: "A curl with an overhand grip, shifting the work to the forearm and brachioradialis." },
  { name: "Rope Triceps Pushdown", group: "Arms", notes: "A cable pushdown on a rope, with the hands splitting apart at the bottom." },
  { name: "Bench Dip", group: "Arms", notes: "A bodyweight dip with the hands behind you on a bench and the feet in front." },
  { name: "Triceps Extension Machine", group: "Arms", notes: "A guided triceps extension with the arms fixed and a set path." },
  { name: "Triceps Kickback", group: "Arms", notes: "A one-arm triceps extension in a bent-over position, squeezing at lockout." },
  { name: "Seated Leg Curl", group: "Legs", notes: "A seated machine curl with the hips bent, stretching the hamstring further." },
  { name: "Seated Calf Raise", group: "Legs", notes: "A calf raise with the knees bent, targeting the soleus underneath." },
  { name: "Leg Press Calf Raise", group: "Legs", notes: "A calf raise done on the leg press sled, with no load on the spine." },
  { name: "Hip Abduction Machine", group: "Legs", notes: "A seated machine that pushes the knees apart, training the outer glute." },
  { name: "Hip Adduction Machine", group: "Legs", notes: "A seated machine that squeezes the knees together, training the inner thigh." },
  { name: "Cable Glute Kickback", group: "Legs", notes: "A one-leg hip extension against a low cable, isolating the glute." },
  { name: "Tibialis Raise", group: "Legs", notes: "Lifting the toes against resistance, training the muscle along the shin." },
  { name: "Captain's Chair Knee Raise", group: "Core", notes: "A knee raise with the forearms supported, removing the grip from the equation." },
  { name: "Sit-Up", group: "Core", notes: "A full curl from lying to sitting, using the abs and the hip flexors together." },
  { name: "Cable Woodchop", group: "Core", notes: "A diagonal cable pull across the body, training rotation under load." },
  { name: "Bird Dog", group: "Core", notes: "An opposite arm and leg reach from all fours, keeping the trunk still." },
  { name: "Copenhagen Plank", group: "Core", notes: "A side plank with the top leg on a bench, loading the inner thigh hard." },
  { name: "Suitcase Carry", group: "Full body", notes: "A carry with weight in one hand only, resisting the lean toward that side." },
  { name: "Front Rack Carry", group: "Full body", notes: "A carry with the weight held at the shoulders, loading the trunk and upper back." },
  { name: "Overhead Carry", group: "Full body", notes: "A walk with the weight locked out overhead, holding the shoulder in position." },
  { name: "Sled Push", group: "Cardio", notes: "Driving a loaded sled forward, a leg workout with no eccentric at all." },
  { name: "Sled Drag", group: "Cardio", notes: "Pulling a loaded sled behind or in front of you with a harness or straps." },
  { name: "Power Clean", group: "Full body", notes: "A barbell pulled explosively from the floor and caught on the shoulders." },
  { name: "Hang Clean", group: "Full body", notes: "A clean starting from the thighs rather than the floor." },
  { name: "Power Snatch", group: "Full body", notes: "A wide-grip barbell pulled from the floor to overhead in one movement." },
  { name: "Barbell High Pull", group: "Full body", notes: "An explosive pull to chest height, training the power phase without the catch." },
  { name: "Kettlebell Clean", group: "Full body", notes: "A kettlebell swung and rotated up into the rack position at the shoulder." },
  { name: "Kettlebell Snatch", group: "Full body", notes: "A kettlebell driven from between the legs to locked out overhead in one movement." },
  { name: "Turkish Get-Up", group: "Full body", notes: "A slow rise from lying to standing with a weight held overhead throughout." },
  { name: "Box Jump", group: "Cardio", notes: "A two-footed jump onto a raised box, training explosive leg power." },
  { name: "Broad Jump", group: "Cardio", notes: "A two-footed jump forward for distance, training horizontal power." },
  { name: "Incline Treadmill Walk", group: "Cardio", notes: "Walking at a steep incline, a hard cardio effort with no impact at all." },
  { name: "Air Bike", group: "Cardio", notes: "A fan bike with moving handles, where resistance rises with your own effort." },
  { name: "Ski Erg", group: "Cardio", notes: "A standing machine pulled from overhead down to the hips, driven by the lats and trunk." },
  { name: "Rope Climb", group: "Back", notes: "Climbing a vertical rope, the most grip-demanding pull there is." },
  { name: "Medicine Ball Slam", group: "Cardio", notes: "Throwing a medicine ball hard into the floor, driven by the lats and trunk." },
  { name: "Rotational Med Ball Throw", group: "Core", notes: "An explosive throw of a medicine ball into a wall, rotating through the hips." },
  { name: "Wrist Curl", group: "Arms", notes: "A small-range curl at the wrist only, training the forearm flexors." },
  { name: "Reverse Wrist Curl", group: "Arms", notes: "A wrist curl in the opposite direction, training the forearm extensors." },
  { name: "Dead Hang", group: "Arms", notes: "Hanging from a bar for time, training grip endurance and decompressing the shoulders." },
  { name: "Neck Extension", group: "Shoulders", notes: "A controlled backward nod against resistance, training the muscles behind the neck." },
  { name: "Neck Flexion", group: "Shoulders", notes: "A controlled forward nod against resistance, training the muscles at the front of the neck." }
].forEach(item => window.EXERCISE_LIBRARY.push(item));

/* Ready-made starter program (back-friendly, low spinal load) —
   installable with one tap from Today / Plan when no block exists. */
window.STARTER_BLOCK = {
  name: 'Back-Friendly Block',
  weeks: 4,
  days: [
    { name: 'Day A', items: [
      { ex: 'Machine Chest Press', sets: 3, repLo: 8, repHi: 10 },
      { ex: 'Lat Pulldown', sets: 3, repLo: 8, repHi: 10 },
      { ex: 'Dumbbell Shoulder Press', sets: 3, repLo: 8, repHi: 10 },
      { ex: 'Leg Extension', sets: 2, repLo: 12, repHi: 15 },
      { ex: 'Dead Bug', sets: 3, repLo: 8, repHi: 8 }
    ]},
    { name: 'Day B', items: [
      { ex: 'Incline Dumbbell Press', sets: 3, repLo: 8, repHi: 10 },
      { ex: 'Chest-Supported Row', sets: 3, repLo: 8, repHi: 10 },
      { ex: 'Lateral Raise', sets: 3, repLo: 12, repHi: 15 },
      { ex: 'Leg Curl', sets: 2, repLo: 12, repHi: 15 },
      { ex: 'Side Plank', sets: 3, repLo: 15, repHi: 20 }
    ]},
    { name: 'Day C', items: [
      { ex: 'Assisted Pull-Up', sets: 3, repLo: 8, repHi: 10 },
      { ex: 'Machine Shoulder Press', sets: 3, repLo: 8, repHi: 10 },
      { ex: 'Cable Crossover', sets: 3, repLo: 10, repHi: 12 },
      { ex: 'Glute Bridge', sets: 2, repLo: 10, repHi: 12 },
      { ex: 'Pallof Press', sets: 3, repLo: 8, repHi: 10 }
    ]}
  ]
};

/* ---------------------------------------------------------------------------
   Movement map — what each exercise IS, not what it is called.

   Every entry is [pattern, ...stress tags]. The pattern drives substitution
   (swap a lift for another that trains the same job); the tags drive the
   injury filter. Filtering on tags rather than names means a new exercise
   only has to be described once, here or by inference, to be handled.
--------------------------------------------------------------------------- */
window.MOVEMENTS = {
  // chest
  'Bench Press':                 ['hpush', 'shoulder'],
  'Incline Dumbbell Press':      ['hpush', 'shoulder'],
  'Dumbbell Fly':                ['fly', 'shoulder'],
  'Push-Up':                     ['hpush', 'shoulder', 'wrist'],
  'Cable Crossover':             ['fly', 'shoulder'],
  'Chest Dip':                   ['hpush', 'shoulder', 'elbow', 'wrist'],
  'Machine Chest Press':         ['hpush'],
  // back
  'Pull-Up':                     ['vpull', 'overhead', 'shoulder', 'elbow', 'grip'],
  'Lat Pulldown':                ['vpull', 'overhead'],
  'Barbell Row':                 ['hpull', 'hinge', 'spineload'],
  'Dumbbell Row':                ['hpull'],
  'Seated Cable Row':            ['hpull'],
  'T-Bar Row':                   ['hpull', 'hinge', 'spineload'],
  'Face Pull':                   ['delt'],
  'Deadlift':                    ['hinge', 'spineload', 'hinge', 'hip', 'grip'],
  'Back Extension':              ['hinge', 'hinge'],
  // shoulders
  'Overhead Press':              ['vpush', 'overhead', 'shoulder', 'spineload', 'neck'],
  'Dumbbell Shoulder Press':     ['vpush', 'overhead', 'shoulder', 'neck'],
  'Lateral Raise':               ['delt', 'shoulder'],
  'Front Raise':                 ['delt', 'shoulder'],
  'Rear Delt Fly':               ['delt'],
  'Arnold Press':                ['vpush', 'overhead', 'shoulder', 'neck'],
  'Upright Row':                 ['delt', 'shoulder', 'neck'],
  'Shrug':                       ['trap', 'neck', 'spineload', 'grip'],
  // arms
  'Barbell Curl':                ['curl', 'elbow', 'wrist'],
  'Dumbbell Curl':               ['curl', 'elbow'],
  'Hammer Curl':                 ['curl', 'elbow'],
  'Preacher Curl':               ['curl', 'elbow'],
  'Concentration Curl':          ['curl', 'elbow'],
  'Triceps Pushdown':            ['tri', 'elbow'],
  'Skull Crusher':               ['tri', 'elbow', 'shoulder'],
  'Overhead Triceps Extension':  ['tri', 'elbow', 'overhead', 'shoulder'],
  'Close-Grip Bench Press':      ['hpush', 'elbow', 'shoulder', 'wrist'],
  // legs
  'Squat':                       ['squat', 'knee', 'hip', 'spineload'],
  'Front Squat':                 ['squat', 'knee', 'hip', 'spineload', 'wrist', 'shoulder'],
  'Goblet Squat':                ['squat', 'knee', 'hip'],
  'Leg Press':                   ['squat', 'knee', 'hip'],
  'Lunge':                       ['lunge', 'knee', 'hip'],
  'Bulgarian Split Squat':       ['lunge', 'knee', 'hip'],
  'Romanian Deadlift':           ['hinge', 'hinge', 'spineload'],
  'Leg Extension':               ['legiso', 'knee'],
  'Leg Curl':                    ['legiso', 'knee'],
  'Hip Thrust':                  ['bridge', 'hip'],
  'Calf Raise':                  ['calf', 'ankle'],
  'Step-Up':                     ['lunge', 'knee', 'hip'],
  'Sumo Deadlift':               ['hinge', 'spineload', 'hinge', 'hip', 'grip'],
  // core
  'Plank':                       ['corebrace', 'wrist'],
  'Side Plank':                  ['corebrace', 'wrist', 'shoulder'],
  'Crunch':                      ['coreflex', 'spineflex', 'neck'],
  'Bicycle Crunch':              ['coreflex', 'spineflex', 'spinerot', 'neck'],
  'Hanging Leg Raise':           ['coreflex', 'spineflex', 'hip', 'overhead', 'shoulder', 'grip'],
  'Russian Twist':               ['corerot', 'spinerot', 'spineflex'],
  'Cable Crunch':                ['coreflex', 'spineflex'],
  'Ab Wheel Rollout':            ['corebrace', 'spineload', 'wrist', 'shoulder'],
  'Mountain Climbers':           ['corebrace', 'wrist', 'knee', 'hip'],
  'Dead Bug':                    ['corebrace'],
  // cardio
  'Treadmill Run':               ['cardio', 'impact', 'knee', 'ankle'],
  'Cycling':                     ['cardio'],
  'Rowing Machine':              ['cardio', 'hinge', 'knee'],
  'Jump Rope':                   ['cardio', 'impact', 'knee', 'ankle'],
  'Stair Climber':               ['cardio', 'knee', 'hip'],
  'Elliptical':                  ['cardio'],
  'Swimming':                    ['cardio', 'overhead', 'shoulder'],
  'HIIT Sprints':                ['cardio', 'impact', 'knee', 'ankle', 'hip'],
  // full body
  'Burpee':                      ['full', 'impact', 'wrist', 'knee', 'spineflex'],
  'Kettlebell Swing':            ['hinge', 'hinge', 'spineload', 'grip'],
  'Clean and Press':             ['full', 'overhead', 'shoulder', 'spineload', 'hinge', 'wrist', 'knee'],
  'Thruster':                    ['full', 'overhead', 'shoulder', 'spineload', 'knee', 'wrist'],
  'Farmer’s Carry':              ['carry', 'grip'],
  'Wall Ball':                   ['full', 'overhead', 'shoulder', 'knee'],
  'Battle Ropes':                ['full', 'shoulder'],
  // joint-friendly additions
  'Chest-Supported Row':         ['hpull'],
  'Machine Shoulder Press':      ['vpush', 'overhead', 'shoulder'],
  'Assisted Pull-Up':            ['vpull', 'overhead', 'shoulder', 'elbow', 'grip'],
  'Glute Bridge':                ['bridge'],
  'Pallof Press':                ['corebrace']
,

  /* --- generated for the exercises added from the content library --- */
  "Low Bar Back Squat": ["squat","knee","hip","shoulder","spineload"],
  "Box Squat": ["squat","knee","hip","spineload"],
  "Safety Squat Bar Squat": ["squat","knee","hip","spineload"],
  "Dumbbell Squat": ["squat","knee","hip","grip"],
  "Smith Machine Squat": ["squat","knee","hip","spineload"],
  "Hack Squat Machine": ["squat","knee","hip"],
  "Pendulum Squat": ["squat","knee","hip"],
  "Belt Squat": ["squat","knee","hip"],
  "Single-Leg Press": ["squat","knee","hip"],
  "Bodyweight Squat": ["squat","knee","hip"],
  "Wall Sit": ["squat","knee"],
  "Pistol Squat": ["squat","knee","hip","ankle"],
  "Trap Bar Deadlift": ["hinge","hinge","hip","knee","spineload","grip"],
  "Dumbbell Romanian Deadlift": ["hinge","hinge","hip","grip"],
  "Single-Leg Romanian Deadlift": ["hinge","hinge","hip","ankle"],
  "Stiff-Leg Deadlift": ["hinge","hinge","hip","spineload","spineflex","grip"],
  "Deficit Deadlift": ["hinge","hinge","hip","knee","spineload","spineflex","grip"],
  "Rack Pull": ["hinge","hinge","hip","spineload","grip"],
  "Good Morning": ["hinge","hinge","hip","spineload","spineflex"],
  "Hip Thrust Machine": ["bridge","hinge","hip"],
  "Glute-Ham Raise": ["hinge","hinge","knee","hip"],
  "Nordic Hamstring Curl": ["hinge","hinge","knee"],
  "Reverse Hyperextension": ["hinge","hinge","hip"],
  "Cable Pull-Through": ["hinge","hinge","hip"],
  "Walking Lunge": ["lunge","knee","hip","ankle","grip"],
  "Reverse Lunge": ["lunge","knee","hip"],
  "Split Squat": ["lunge","knee","hip"],
  "Lateral Lunge": ["lunge","knee","hip"],
  "Curtsy Lunge": ["lunge","knee","hip","spinerot"],
  "Smith Machine Split Squat": ["lunge","knee","hip","spineload"],
  "Incline Barbell Bench Press": ["hpush","shoulder","elbow","wrist"],
  "Decline Barbell Bench Press": ["hpush","shoulder","elbow"],
  "Floor Press": ["hpush","shoulder","elbow"],
  "Dumbbell Bench Press": ["hpush","shoulder","elbow"],
  "Smith Machine Bench Press": ["hpush","shoulder","elbow"],
  "Incline Push-Up": ["hpush","shoulder","elbow","wrist"],
  "Deficit Push-Up": ["hpush","shoulder","elbow"],
  "Assisted Dip Machine": ["hpush","shoulder","elbow"],
  "Pec Deck / Machine Fly": ["fly","shoulder"],
  "Push Press": ["vpush","shoulder","knee","overhead","spineload"],
  "Seated Dumbbell Press": ["vpush","shoulder","elbow","overhead"],
  "Landmine Press": ["vpush","shoulder","elbow"],
  "Seated Z-Press": ["vpush","shoulder","overhead","hip"],
  "Pike Push-Up": ["vpush","shoulder","elbow","wrist","overhead"],
  "Handstand Push-Up": ["vpush","shoulder","elbow","wrist","overhead"],
  "Chin-Up": ["vpull","shoulder","elbow","overhead","grip"],
  "Neutral-Grip Pull-Up": ["vpull","shoulder","elbow","overhead","grip"],
  "Close-Grip Lat Pulldown": ["vpull","shoulder","elbow","overhead"],
  "Single-Arm Lat Pulldown": ["vpull","shoulder","elbow","overhead"],
  "Straight-Arm Pulldown": ["vpull","shoulder","overhead"],
  "Seated Row Machine": ["hpull","shoulder","elbow"],
  "Inverted Row": ["hpull","shoulder","elbow","grip"],
  "Suspension Trainer Row": ["hpull","shoulder","elbow","grip"],
  "Meadows Row": ["hpull","shoulder","elbow","spinerot","grip"],
  "Seal Row": ["hpull","shoulder","elbow"],
  "Cable Lateral Raise": ["delt","shoulder"],
  "Lateral Raise Machine": ["delt","shoulder"],
  "Rear Delt Fly Machine": ["delt","shoulder"],
  "Dumbbell Shrug": ["trap","shoulder","grip"],
  "Cable External Rotation": ["delt","shoulder"],
  "Band Pull-Apart": ["delt","shoulder"],
  "EZ-Bar Curl": ["curl","elbow"],
  "Incline Dumbbell Curl": ["curl","elbow","shoulder"],
  "Cable Biceps Curl": ["curl","elbow"],
  "Biceps Curl Machine": ["curl","elbow"],
  "Reverse Curl": ["curl","elbow","wrist"],
  "Rope Triceps Pushdown": ["tri","elbow"],
  "Bench Dip": ["tri","shoulder","elbow","wrist"],
  "Triceps Extension Machine": ["tri","elbow"],
  "Triceps Kickback": ["tri","elbow","spineflex"],
  "Seated Leg Curl": ["legiso","knee"],
  "Seated Calf Raise": ["calf","ankle"],
  "Leg Press Calf Raise": ["calf","ankle"],
  "Hip Abduction Machine": ["legiso","hip"],
  "Hip Adduction Machine": ["legiso","hip"],
  "Cable Glute Kickback": ["legiso","hip"],
  "Tibialis Raise": ["legiso","ankle"],
  "Captain's Chair Knee Raise": ["corebrace","hip"],
  "Sit-Up": ["coreflex","hip","spineflex"],
  "Cable Woodchop": ["corerot","spinerot"],
  "Bird Dog": ["corebrace"],
  "Copenhagen Plank": ["corebrace","hip"],
  "Suitcase Carry": ["carry","shoulder","grip"],
  "Front Rack Carry": ["carry","shoulder","spineload","wrist"],
  "Overhead Carry": ["carry","shoulder","overhead","spineload"],
  "Sled Push": ["cardio","knee","hip","ankle"],
  "Sled Drag": ["cardio","knee","hip"],
  "Power Clean": ["full","hip","knee","shoulder","wrist","spineload","impact"],
  "Hang Clean": ["full","hip","knee","shoulder","wrist"],
  "Power Snatch": ["full","hip","knee","shoulder","overhead","impact"],
  "Barbell High Pull": ["full","shoulder","hip"],
  "Kettlebell Clean": ["full","hip","shoulder","wrist","grip"],
  "Kettlebell Snatch": ["full","hip","shoulder","overhead","grip"],
  "Turkish Get-Up": ["carry","shoulder","hip","knee","wrist","overhead"],
  "Box Jump": ["cardio","knee","hip","ankle","impact"],
  "Broad Jump": ["cardio","knee","hip","ankle","impact"],
  "Incline Treadmill Walk": ["cardio","hip","ankle"],
  "Air Bike": ["cardio","knee","hip","shoulder"],
  "Ski Erg": ["cardio","shoulder","overhead","spineflex"],
  "Rope Climb": ["vpull","shoulder","elbow","grip","overhead"],
  "Medicine Ball Slam": ["cardio","shoulder","overhead","spineflex"],
  "Rotational Med Ball Throw": ["corerot","spinerot"],
  "Wrist Curl": ["curl","wrist"],
  "Reverse Wrist Curl": ["curl","wrist"],
  "Dead Hang": ["curl","shoulder","grip","overhead"],
  "Neck Extension": ["corebrace","neck"],
  "Neck Flexion": ["corebrace","neck"]
};

/* Patterns that can stand in for each other when the exact one is ruled out. */
window.MOVE_FAMILY = {
  hpush: 'push', vpush: 'push', fly: 'push', tri: 'push',
  hpull: 'pull', vpull: 'pull', delt: 'pull', trap: 'pull', curl: 'pull',
  squat: 'legs', lunge: 'legs', legiso: 'legs', calf: 'legs',
  hinge: 'legs', bridge: 'legs',
  coreflex: 'core', corerot: 'core', corebrace: 'core', carry: 'core',
  cardio: 'cardio', full: 'full'
};

/* Anything not in the map is read from its name, then its muscle group, so a
   new exercise is described rather than waved through. Order matters —
   "leg curl" must be caught before "curl". */
window.MOVE_INFER = [
  [/leg\s*curl|hamstring curl/i,                    ['legiso', 'knee']],
  [/leg\s*extension|knee extension/i,               ['legiso', 'knee']],
  [/calf|heel raise/i,                              ['calf', 'ankle']],
  [/pull[-\s]?up|chin[-\s]?up|pulldown|lat pull/i,  ['vpull', 'overhead', 'shoulder', 'elbow', 'grip']],
  [/\brow\b/i,                                      ['hpull']],
  [/shrug/i,                                        ['trap', 'neck', 'spineload', 'grip']],
  [/deadlift|good ?morning|hip hinge|kettlebell swing|swing/i, ['hinge', 'hinge', 'spineload', 'hip', 'grip']],
  [/hip thrust|glute bridge|bridge/i,               ['bridge', 'hip']],
  [/split squat|lunge|step[-\s]?up/i,               ['lunge', 'knee', 'hip']],
  [/squat|leg press|hack/i,                         ['squat', 'knee', 'hip', 'spineload']],
  [/overhead press|shoulder press|military|push press|jerk|snatch|handstand/i, ['vpush', 'overhead', 'shoulder', 'neck']],
  [/upright row|lateral raise|front raise|delt|rear fly/i, ['delt', 'shoulder']],
  [/overhead (triceps|tricep|extension)/i,          ['tri', 'elbow', 'overhead', 'shoulder']],
  [/pushdown|skull ?crusher|triceps|tricep|kickback/i, ['tri', 'elbow']],
  [/curl/i,                                         ['curl', 'elbow']],
  [/dip\b/i,                                        ['hpush', 'shoulder', 'elbow', 'wrist']],
  [/push[-\s]?up|press[-\s]?up/i,                   ['hpush', 'shoulder', 'wrist']],
  [/landmine/i,                                     ['vpush', 'shoulder']],
  [/sled|prowler/i,                                 ['cardio', 'knee', 'impact']],
  [/bench|chest press|floor press/i,                ['hpush', 'shoulder']],
  [/fly|flye|crossover|pec deck/i,                  ['fly', 'shoulder']],
  [/plank|dead ?bug|pallof|bird ?dog|hollow/i,      ['corebrace']],
  [/twist|woodchop|rotation/i,                      ['corerot', 'spinerot', 'spineflex']],
  [/crunch|sit[-\s]?up|leg raise|knee raise/i,      ['coreflex', 'spineflex', 'neck']],
  [/carry|farmer|suitcase/i,                        ['carry', 'grip']],
  [/sprint|run|jog|jump|skip|burpee|box jump/i,     ['cardio', 'impact', 'knee', 'ankle']],
  [/cycl|bike|elliptical|swim|walk|stair|erg|rower|rowing machine/i, ['cardio']]
];

/* Last resort: judge by muscle group, erring towards caution. */
window.MOVE_BY_GROUP = {
  Chest: ['hpush', 'shoulder'],
  Back: ['hpull'],
  Shoulders: ['delt', 'shoulder'],
  Arms: ['curl', 'elbow'],
  Legs: ['squat', 'knee', 'hip'],
  Core: ['corebrace', 'spineflex'],
  Cardio: ['cardio', 'impact', 'knee', 'ankle'],
  'Full body': ['full', 'spineload', 'shoulder', 'knee']
};

/* ---------------------------------------------------------------------------
   Equipment — what a lift needs to exist. Owning less is a filter, same as an
   injury: anything asking for kit you have switched off drops out of the
   builder. Bodyweight is always on, so a home setup still has a plan.
--------------------------------------------------------------------------- */
window.EQUIPMENT = [
  { key: 'bodyweight', label: 'Bodyweight', sec: 'Free weights & basics', always: true },
  { key: 'barbell',    label: 'Barbell',        sec: 'Free weights & basics' },
  { key: 'dumbbell',   label: 'Dumbbells',      sec: 'Free weights & basics' },
  { key: 'kettlebell', label: 'Kettlebell',     sec: 'Free weights & basics' },
  { key: 'bench',      label: 'Bench',          sec: 'Free weights & basics' },
  { key: 'rack',       label: 'Rack',           sec: 'Free weights & basics' },
  { key: 'cable',      label: 'Cable tower',    sec: 'Free weights & basics' },
  { key: 'bar',        label: 'Pull-up bar',    sec: 'Free weights & basics' },
  { key: 'band',       label: 'Bands',          sec: 'Free weights & basics' },
  { key: 'mat',        label: 'Mat',            sec: 'Free weights & basics' },
  { key: 'ball',       label: 'Ball',           sec: 'Free weights & basics' },
  { key: 'rope',       label: 'Rope',           sec: 'Free weights & basics' },
  { key: 'wheel',      label: 'Ab wheel',       sec: 'Free weights & basics' },
  { key: 'cardio',     label: 'Cardio machine', sec: 'Machines' },
  { key: 'm-press',    label: 'Chest press',    sec: 'Machines' },
  { key: 'm-shoulder', label: 'Shoulder press', sec: 'Machines' },
  { key: 'm-pulldown', label: 'Lat pulldown',   sec: 'Machines' },
  { key: 'm-row',      label: 'Row machine',    sec: 'Machines' },
  { key: 'm-legpress', label: 'Leg press',      sec: 'Machines' },
  { key: 'm-legext',   label: 'Leg extension',  sec: 'Machines' },
  { key: 'm-legcurl',  label: 'Leg curl',       sec: 'Machines' },
  { key: 'm-back',     label: 'Back extension', sec: 'Machines' },
  { key: 'm-assist',   label: 'Assisted pull-up', sec: 'Machines' },
  { key: 'machine',    label: 'Other machine',  sec: 'Machines' },
  { key: 'pool',       label: 'Pool',           sec: 'Machines' }
];

window.EXERCISE_EQUIP = {
  'Bench Press': ['barbell', 'bench', 'rack'],
  'Incline Dumbbell Press': ['dumbbell', 'bench'],
  'Dumbbell Fly': ['dumbbell', 'bench'],
  'Push-Up': ['bodyweight'],
  'Cable Crossover': ['cable'],
  'Chest Dip': ['bar'],
  'Machine Chest Press': ['m-press'],
  'Pull-Up': ['bar'],
  'Lat Pulldown': ['m-pulldown'],
  'Barbell Row': ['barbell'],
  'Dumbbell Row': ['dumbbell', 'bench'],
  'Seated Cable Row': ['cable'],
  'T-Bar Row': ['barbell'],
  'Face Pull': ['cable'],
  'Deadlift': ['barbell'],
  'Back Extension': ['m-back'],
  'Overhead Press': ['barbell', 'rack'],
  'Dumbbell Shoulder Press': ['dumbbell'],
  'Lateral Raise': ['dumbbell'],
  'Front Raise': ['dumbbell'],
  'Rear Delt Fly': ['dumbbell'],
  'Arnold Press': ['dumbbell'],
  'Upright Row': ['barbell'],
  'Shrug': ['dumbbell'],
  'Barbell Curl': ['barbell'],
  'Dumbbell Curl': ['dumbbell'],
  'Hammer Curl': ['dumbbell'],
  'Preacher Curl': ['bench', 'dumbbell'],
  'Concentration Curl': ['dumbbell', 'bench'],
  'Triceps Pushdown': ['cable'],
  'Skull Crusher': ['barbell', 'bench'],
  'Overhead Triceps Extension': ['dumbbell'],
  'Close-Grip Bench Press': ['barbell', 'bench', 'rack'],
  'Squat': ['barbell', 'rack'],
  'Front Squat': ['barbell', 'rack'],
  'Goblet Squat': ['dumbbell'],
  'Leg Press': ['m-legpress'],
  'Lunge': ['bodyweight'],
  'Bulgarian Split Squat': ['bench'],
  'Romanian Deadlift': ['barbell'],
  'Leg Extension': ['m-legext'],
  'Leg Curl': ['m-legcurl'],
  'Hip Thrust': ['barbell', 'bench'],
  'Calf Raise': ['bodyweight'],
  'Step-Up': ['bench'],
  'Sumo Deadlift': ['barbell'],
  'Plank': ['mat'],
  'Side Plank': ['mat'],
  'Crunch': ['mat'],
  'Bicycle Crunch': ['mat'],
  'Hanging Leg Raise': ['bar'],
  'Russian Twist': ['mat'],
  'Cable Crunch': ['cable'],
  'Ab Wheel Rollout': ['wheel'],
  'Mountain Climbers': ['bodyweight'],
  'Dead Bug': ['mat'],
  'Treadmill Run': ['cardio'],
  'Cycling': ['cardio'],
  'Rowing Machine': ['cardio'],
  'Jump Rope': ['rope'],
  'Stair Climber': ['cardio'],
  'Elliptical': ['cardio'],
  'Swimming': ['pool'],
  'HIIT Sprints': ['bodyweight'],
  'Burpee': ['bodyweight'],
  'Kettlebell Swing': ['kettlebell'],
  'Clean and Press': ['barbell'],
  'Thruster': ['barbell'],
  'Farmer’s Carry': ['dumbbell'],
  'Wall Ball': ['ball'],
  'Battle Ropes': ['rope'],
  'Chest-Supported Row': ['m-row'],
  'Machine Shoulder Press': ['m-shoulder'],
  'Assisted Pull-Up': ['m-assist'],
  'Glute Bridge': ['mat'],
  'Pallof Press': ['cable']
,

  /* --- generated for the exercises added from the content library --- */
  "Low Bar Back Squat": ["barbell","rack"],
  "Box Squat": ["barbell","rack"],
  "Safety Squat Bar Squat": ["barbell"],
  "Dumbbell Squat": ["dumbbell"],
  "Smith Machine Squat": ["machine"],
  "Hack Squat Machine": ["machine"],
  "Pendulum Squat": ["machine"],
  "Belt Squat": ["machine"],
  "Single-Leg Press": ["m-legpress"],
  "Bodyweight Squat": ["bodyweight"],
  "Wall Sit": ["bodyweight"],
  "Pistol Squat": ["bodyweight"],
  "Trap Bar Deadlift": ["barbell"],
  "Dumbbell Romanian Deadlift": ["dumbbell"],
  "Single-Leg Romanian Deadlift": ["dumbbell"],
  "Stiff-Leg Deadlift": ["barbell"],
  "Deficit Deadlift": ["barbell"],
  "Rack Pull": ["barbell"],
  "Good Morning": ["barbell","rack"],
  "Hip Thrust Machine": ["machine"],
  "Glute-Ham Raise": ["machine"],
  "Nordic Hamstring Curl": ["bodyweight"],
  "Reverse Hyperextension": ["machine"],
  "Cable Pull-Through": ["cable"],
  "Walking Lunge": ["dumbbell"],
  "Reverse Lunge": ["dumbbell"],
  "Split Squat": ["dumbbell"],
  "Lateral Lunge": ["dumbbell"],
  "Curtsy Lunge": ["dumbbell"],
  "Smith Machine Split Squat": ["machine"],
  "Incline Barbell Bench Press": ["barbell","rack","bench"],
  "Decline Barbell Bench Press": ["barbell","rack","bench"],
  "Floor Press": ["barbell","rack","bench"],
  "Dumbbell Bench Press": ["dumbbell","bench"],
  "Smith Machine Bench Press": ["machine","bench"],
  "Incline Push-Up": ["bench"],
  "Deficit Push-Up": ["bodyweight"],
  "Assisted Dip Machine": ["m-assist"],
  "Pec Deck / Machine Fly": ["machine"],
  "Push Press": ["barbell","rack","bench"],
  "Seated Dumbbell Press": ["dumbbell","bench"],
  "Landmine Press": ["barbell"],
  "Seated Z-Press": ["barbell","rack","bench"],
  "Pike Push-Up": ["bodyweight"],
  "Handstand Push-Up": ["bodyweight"],
  "Chin-Up": ["bar"],
  "Neutral-Grip Pull-Up": ["bar"],
  "Close-Grip Lat Pulldown": ["m-pulldown"],
  "Single-Arm Lat Pulldown": ["cable"],
  "Straight-Arm Pulldown": ["cable"],
  "Seated Row Machine": ["m-row"],
  "Inverted Row": ["bodyweight"],
  "Suspension Trainer Row": ["rope"],
  "Meadows Row": ["barbell"],
  "Seal Row": ["barbell","bench"],
  "Cable Lateral Raise": ["cable"],
  "Lateral Raise Machine": ["machine"],
  "Rear Delt Fly Machine": ["machine"],
  "Dumbbell Shrug": ["dumbbell"],
  "Cable External Rotation": ["cable"],
  "Band Pull-Apart": ["band"],
  "EZ-Bar Curl": ["barbell"],
  "Incline Dumbbell Curl": ["dumbbell","bench"],
  "Cable Biceps Curl": ["cable"],
  "Biceps Curl Machine": ["machine"],
  "Reverse Curl": ["barbell"],
  "Rope Triceps Pushdown": ["cable"],
  "Bench Dip": ["bar"],
  "Triceps Extension Machine": ["machine"],
  "Triceps Kickback": ["dumbbell"],
  "Seated Leg Curl": ["m-legcurl"],
  "Seated Calf Raise": ["machine"],
  "Leg Press Calf Raise": ["m-legpress"],
  "Hip Abduction Machine": ["machine"],
  "Hip Adduction Machine": ["machine"],
  "Cable Glute Kickback": ["cable"],
  "Tibialis Raise": ["mat"],
  "Captain's Chair Knee Raise": ["machine"],
  "Sit-Up": ["mat"],
  "Cable Woodchop": ["cable"],
  "Bird Dog": ["mat"],
  "Copenhagen Plank": ["mat"],
  "Suitcase Carry": ["dumbbell"],
  "Front Rack Carry": ["kettlebell"],
  "Overhead Carry": ["kettlebell"],
  "Sled Push": ["cardio"],
  "Sled Drag": ["cardio"],
  "Power Clean": ["barbell"],
  "Hang Clean": ["barbell"],
  "Power Snatch": ["barbell"],
  "Barbell High Pull": ["barbell"],
  "Kettlebell Clean": ["kettlebell"],
  "Kettlebell Snatch": ["kettlebell"],
  "Turkish Get-Up": ["kettlebell"],
  "Box Jump": ["bodyweight"],
  "Broad Jump": ["bodyweight"],
  "Incline Treadmill Walk": ["cardio"],
  "Air Bike": ["cardio"],
  "Ski Erg": ["cardio"],
  "Rope Climb": ["rope"],
  "Medicine Ball Slam": ["ball"],
  "Rotational Med Ball Throw": ["ball"],
  "Wrist Curl": ["dumbbell","bench"],
  "Reverse Wrist Curl": ["dumbbell","bench"],
  "Dead Hang": ["bar"],
  "Neck Extension": ["bodyweight"],
  "Neck Flexion": ["bodyweight"]
};

/* Same idea as the movement tags: an exercise typed in by hand is read from
   its name so it cannot dodge the filter. Unknown means bodyweight, which is
   always available — a guess should never hide something you own. */
window.EQUIP_INFER = [
  [/barbell|bench press|deadlift|squat|clean|snatch|thruster|good ?morning/i, ['barbell']],
  [/dumbbell|db\b|goblet|hammer curl|farmer/i, ['dumbbell']],
  [/kettlebell|kb\b|swing/i, ['kettlebell']],
  [/cable|pushdown|crossover|pallof|pec deck/i, ['cable']],
  [/lat ?pulldown|pulldown/i,                  ['m-pulldown']],
  [/leg press/i,                               ['m-legpress']],
  [/leg extension/i,                           ['m-legext']],
  [/assisted/i,                                ['m-assist']],
  [/machine|press machine/i,                   ['machine']],
  [/pull[-\s]?up|chin[-\s]?up|hanging|dip\b/i, ['bar']],
  [/band|resistance band/i, ['band']],
  [/treadmill|cycl|bike|elliptical|stair|erg|rowing machine/i, ['cardio']],
  [/rope/i, ['rope']],
  [/wall ball|med(icine)? ball|slam ball/i, ['ball']],
  [/ab wheel|rollout/i, ['wheel']],
  [/swim/i, ['pool']],
  [/plank|crunch|sit[-\s]?up|dead ?bug|bird ?dog|bridge|twist/i, ['mat']],
  [/bench|step[-\s]?up|split squat|preacher/i, ['bench']]
];

/* ---- Content layer ----------------------------------------------------
   data/exercise-content.json is keyed by its own ids. Most of this catalog's
   `demo` slugs match those ids exactly; these are the ones that don't.
   Anything absent from both stays uncovered and falls back to its own notes —
   Swimming and Bicycle Crunch have no equivalent in the content set. */
window.CONTENT_ALIAS = {
  'incline-dumbbell-press': 'db-incline-press',
  'dumbbell-fly': 'db-fly',
  'cable-crossover': 'cable-fly',
  'chest-dip': 'dip',
  'dumbbell-row': 'db-row',
  'deadlift': 'conventional-deadlift',
  'dumbbell-shoulder-press': 'db-shoulder-press',
  'shrug': 'barbell-shrug',
  'dumbbell-curl': 'db-curl',
  'skull-crusher': 'skullcrusher',
  'close-grip-bench-press': 'close-grip-bench',
  'squat': 'back-squat',
  'lunge': 'forward-lunge',
  'romanian-deadlift': 'rdl',
  'leg-curl': 'lying-leg-curl',
  'calf-raise': 'standing-calf-raise',
  'ab-wheel-rollout': 'ab-wheel',
  'mountain-climbers': 'mountain-climber',
  'cycling': 'stationary-bike',
  'rowing-machine': 'rowing-erg',
  'hiit-sprints': 'treadmill-run',
  'kettlebell-swing': 'kb-swing',
  'clean-and-press': 'clean-and-jerk',
  'thruster': 'kb-goblet-clean',
  'burpee': 'burpee',
  'farmers-carry': 'farmers-carry'
};

/* The three catalog items with no demo slug, matched by name instead. */
window.CONTENT_BY_NAME = {
  'burpee': 'burpee',
  'farmer’s carry': 'farmers-carry',
  "farmer's carry": 'farmers-carry'
};
